### ISSUE TITLE
MCEdit.v1.5.2.0 64bit Crash

### ISSUE THREAD

**Issue by ErikSteiner** [Khroki/MCEdit-Unified#631] opened 2016-04-02 15:29 UTC
If I want to choose a selection of chunks in the Chunk View the editor will crash.

Running in fixed mode. Support files are in your Documents folder.
Splash load...
[ WARNING][            mcplatform.py:1182]:Initializing window management...
Minecraft_Server.jar storage initialized.
Each server is stored in a subdirectory of E:\Documents\MCEdit\ServerJarStorage named with the server's version number
Cached servers:  [u'Release 1.8.9']
[ WARNING][          version_utils.py:365]:Encountered a HTTPError while trying to access "https://sessionserver.mojang.com/session/minecraft/profile/dea8c7d97aab3dc8af077917f942a87d"
[ WARNING][          version_utils.py:366]:Error: 429
mcedit.main MCEdit exited with errors.
[   ERROR][                  root.py:1004]:MCEdit version Unified v1.5.2.0 %s Minecraft 1.8/1.9 | PE 0.11
[   ERROR][                  root.py:1007]:'NoneType' object is not iterable
Traceback (most recent call last):
  File "<string>", line 1001, in main
  File "<string>", line 845, in main
  File "albow\root.py", line 168, in run
  File "albow\root.py", line 233, in run_modal
  File "albow\widget.py", line 787, in gl_draw_all
  File "albow\widget.py", line 787, in gl_draw_all
  File "albow\widget.py", line 787, in gl_draw_all
  File "albow\widget.py", line 787, in gl_draw_all
  File "albow\widget.py", line 784, in gl_draw_all
  File "albow\openglwidgets.py", line 22, in gl_draw_self
  File "albow\openglwidgets.py", line 28, in gl_draw_viewport
  File "viewports\camera.py", line 1832, in gl_draw
  File "viewports\chunk.py", line 83, in render
  File "viewports\camera.py", line 1859, in render
  File "albow\root.py", line 611, in update_tooltip
  File "albow\root.py", line 597, in show_tooltip
  File "viewports\chunk.py", line 87, in tooltipText
  File "viewports\camera.py", line 1631, in tooltipText
  File "editortools\chunk.py", line 195, in worldTooltipText
  File "editortools\select.py", line 725, in selectionBoxInProgress
  File "editortools\editortool.py", line 262, in selectionBoxForCorners
TypeError: 'NoneType' object is not iterable
Press RETURN or close this window to dismiss.

**Comment by naor2013** [comment] 2016-04-02 16:36
duplicate of #629 so I'm closing this one but thanks for the report :D

**Closed by naor2013** 2016-04-02 16:36 UTC
