### ISSUE TITLE
Hud Dissapering & fill item not appearing

### ISSUE THREAD

**Issue by TheMaxShaft** [Khroki/MCEdit-Unified#390] opened 2015-05-09 20:58 UTC
Without changing settings, the HUD is disappearing, also the item in fill doesn't appear
![screen shot 2015-05-09 at 4 58 14 pm](https://cloud.githubusercontent.com/assets/10644674/7552022/9c215b52-f66c-11e4-9b18-b13ce2d5db1a.png)

**Comment by Rubisk** [comment] 2015-05-09 22:21
Try check the console for any errors.
Is there any way we can reliably reproduce? Did restarting fix it?

What's your OS, what graphics card do you have and did you make sure your drivers aren't outdated?

**Comment by TheMaxShaft** [comment] 2015-05-22 23:23
I use OS X (Newest version) Restarting didn't fix it, graphics card is Intel HD Graphics 4000 1024 MB

**Comment by TrazLander** [comment] 2015-05-26 16:26
Cannot reproduce, and we're going to have to close this unless you list exact steps to reproduce. So the toolbar is gone? Or the block picker? or what. I'm confused.

**Comment by Khroki** [comment] 2015-06-10 20:45
No response for 2 weeks, reopen if it's still a problem/you have more info.

**Comment by TheMaxShaft** [comment] 2015-06-27 19:50
i just reinstalled it, if there is a button i accidentally pressed to make the hud disappear, it is still not appearing, i am on the newest version now, still not there

**Comment by Rubisk** [comment] 2015-06-27 23:16
Do you have the output of the mcedit.log file?

**Comment by TheMaxShaft** [comment] 2015-07-07 01:35
https://copy.com/HFZeKuLlsTXTZOyv

is this it

**Comment by TrazLander** [comment] 2015-07-08 09:34
....wait a second. So is that screenshot fully what you see on your screen? The hud's not missing it's just running off the bottom of your screen. Can you maximize the program?

**Comment by Khroki** [comment] 2015-09-05 17:29
Assuming that was the problem, closing since it's been 2 months.

**Closed by Khroki** 2015-09-05 17:29 UTC
