### ISSUE TITLE
MCEdit won't start...

### ISSUE THREAD

**Issue by silentdude247** [Khroki/MCEdit-Unified#696] opened 2016-07-06 07:44 UTC
I've been trying to run MCEdit 1.5.3.0 (64 bit) on my computer but it just refuses to run properly no matter what I do. I've tried searching for a solution on other threads but nothing seems to work for me. I've taken a screenshot in the hopes that it will somewhat help, and I expect a lot of people will look at it and think just how much of a noob I am, but can someone just please tell me how to fix the damn thing. I have read the code, I just have no idea what the heck any of it means.
![capture](https://cloud.githubusercontent.com/assets/20315505/16610857/132ddaac-43b2-11e6-8c65-41698df0db98.PNG)

**Comment by LaChal** [comment] 2016-07-06 19:13
According to the screen-shot, you have a video driver issue.

Depending the version of Windows you're running on, you may want to upgrade it or install a prior version.

Searching with the keywords 'mcedit' and 'glWindowPos2d' (on this Github repo and more generally in any search engine) may give you some other related issues and their solution.

Please, if you can solve this, just post here, so we can close this issue :smile:
(Post here too if you can't, of course :wink:)

**Comment by silentdude247** [comment] 2016-07-06 23:37
Thanks LaChal...still haven't found a suitable solution yet, but thank you for bringing up the issue with the video driver, that would never have occurred to me, not that I know how to fix that problem.

And I should probably mention I'm running Windows 10. I had a slight feeling that it may have something to do with my version of windows, because a couple years back I used to use MCEdit quite often, except back then I was running MCEdit on my Windows Vista computer (which I no longer have) and it ran just fine. But now that I'm on a new computer and running Windows 10, it just doesn't seem to work the same anymore. Could it be possible that MCEdit hasn't yet been optimized to run on Windows 10?

**Comment by thebigsmileXD** [comment] 2016-07-14 07:24
Exactly the same for me ;)

@silentdude247 does minecraft itself work for you? for me it doesn't

**Comment by HimbeersaftLP** [comment] 2016-07-14 07:56
Oh, @thebigsmileXD you're here, too xD

**Comment by LaChal** [comment] 2016-07-14 10:31
Since several people reported the same type of error concerning Windows 10 and OpenGL, we can't do much ourselves...

Looks like the OpenGL version on Windows 10 video drivers miss some functions.

You can find information in other reports: #692, #636

**Comment by codewarrior0** [comment] 2016-07-14 10:47
> Looks like the OpenGL version on Windows 10 video drivers miss some functions.

It's more likely that the display context is getting a software-based OpenGL renderer instead of the hardware-based one provided by the GPU driver. The software renderer provided by Windows only supports GL version 1.1, which doesn't provide glWindowPos since it is a GL 1.4 feature. You don't ever want to use the software renderer because it will be very slow and will never use the hardware GPU.

To aid in debugging this problem, you should, immediately after [initializing the display context via `pygame.set_mode`](https://github.com/Khroki/MCEdit-Unified/blob/master/utilities/gl_display_context.py#L51), ask the GL for version and renderer info and print/log the info. The version and renderer info can be obtained by calling:

`GL.glGetString(GL.GL_VERSION), GL.glGetString(GL.GL_VENDOR), GL.glGetString(GL.GL_RENDERER)`

[Example code.](https://github.com/mcedit/mcedit2/blob/6055a4d35cbb1cc698060fcf15666904b6f1e8f0/src/mcedit2/util/qglcontext.py#L34)

**Comment by silentdude247** [comment] 2016-07-14 11:07
I am so confused right now...

**Comment by codewarrior0** [comment] 2016-07-14 12:07
No. The problem *may be* that MCEdit is trying to use a software renderer instead of using the GPU. This is a problem on any operating system.

The directions I gave are for the developers to find out if this is actually the case.

**Comment by silentdude247** [comment] 2016-07-14 12:26
Oh, right

**Comment by Khroki** [comment] 2016-07-15 02:28
Yeah, sorry for lack of action, I got a full time job so time has been sparse.

**Comment by silentdude247** [comment] 2016-07-15 05:28
Ok, tried updating my video driver and as you can tell from the screenshots, it obviously didn't make any difference so...I'm at a loss.
![videodriver](https://cloud.githubusercontent.com/assets/20315505/16864514/623f976a-4ab1-11e6-9ee0-3e1853f1d448.PNG)
![videodriverupdate](https://cloud.githubusercontent.com/assets/20315505/16864520/70fcbde6-4ab1-11e6-8ec1-fdf500bfa335.PNG)
![extra](https://cloud.githubusercontent.com/assets/20315505/16864521/7a52bd00-4ab1-11e6-84a2-22bde7453a40.PNG)

**Comment by Khroki** [comment] 2016-07-18 11:09
The problem is drivers with Microsoft Corporation in their name typically don't support OpenGL 1.4 functionality since they are semi-generic drivers only tested with DirectX and OpenGL 1.1, nothing to do with Windows 10 specifically and some Windows 8 machines have the same issue. You need to go to the driver manufacturer's website and find a driver from them. If they don't have a windows 10 driver you may need to install one designed for a previous windows version.

**Comment by silentdude247** [comment] 2016-07-19 12:12
Thanks 👍

**Comment by thebigsmileXD** [comment] 2016-07-19 13:40
A new little note: Checked on my Windows 8 machine without any change in the system. It worked fine before, installed the latest version and only this doesn't work anymore. i guess i had 1.6 before.

**Comment by LaChal** [comment] 2016-07-19 21:15
Some video driver for Windows may have dropped support for some OpenGL versions.
We are looking for a solution/workaround on our side.

**Comment by thebigsmileXD** [comment] 2016-07-21 07:06
@LaChal i am sure the old MCEdit versions also used OpenGL. The old MCEdit works, only the new one doesn't

**Comment by LaChal** [comment] 2016-07-21 19:29
@thebigsmileXD I'm sure that the piece of code which annoy us now worked fine one year ago when it was written and first released.
The fact is since Windows 10 is out we encounter this issue with some Intel video chipset which driver can't support OpenGL version that drivers for the same chipset supported for older systems...
Hard to debug on our side, because we don't have such chipset.

**Comment by Khroki** [comment] 2016-07-22 01:50
If you know a version that works with these integrated chipsets under windows 10, let us know what version it is so we can see what changed. Also by new version do you mean 1.5.x or 2.x?

**Comment by silentdude247** [comment] 2016-07-22 01:54
Will do. Thanks

**Comment by Khroki** [comment] 2016-07-23 01:01
Could you test this build? Http:\\lavaexpert.org\mceditgl1.1.zip

**Comment by Khroki** [comment] 2016-07-23 01:14
I think you'll be surprised what it'll run on now
![untitled](https://cloud.githubusercontent.com/assets/5132390/17074884/46aad51e-5051-11e6-8d71-279172c89683.png)

**Comment by Khroki** [comment] 2016-07-24 13:54
Calling this fixed for next release.

**Closed by Khroki** 2016-07-24 13:54 UTC

**Comment by thebigsmileXD** [comment] 2016-07-25 07:15
Thank you! i'll try out the latest build.

**Comment by silentdude247** [comment] 2016-07-25 08:00
Still doesn't seem to work, it still crashes when I try to open it...

**Comment by Khroki** [comment] 2016-07-25 11:11
Oh I thought you guys had tested it already, the test build is not on the official site since it is a test. HTTP:\\\lavaexpert.org\mceditgl1.1.zip

**Comment by thebigsmileXD** [comment] 2016-07-25 11:57
Totally does work fine!

**Comment by silentdude247** [comment] 2016-07-25 20:41
Thank you for putting the link back up
