### ISSUE TITLE
Trying to open MCEdit on OS X crashes instantly

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [Khroki/MCEdit-Unified#305] opened 2015-02-13 17:04 UTC
After it stops bouncing, the icon changes to that python holding the SNES controller, and then a dialouge box shows up saying "mcedit error".  The two buttons show terminate, and open console.

Here should be all the stuff in the console.

15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	Splash load...
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	Traceback (most recent call last):
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	  File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	    _run()
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	  File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	    exec(compile(source, path, 'exec'), globals(), globals())
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	  File "/Users/carlarogers/Desktop/mcedit.app/Contents/Resources/mcedit.py", line 12, in <module>
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	    import splash
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	  File "splash.pyc", line 10, in <module>
15-02-13 10:07:21 AM	[0x0-0x34034].org.pythonmac.unspecified.mcedit[643]	pygame.error: File is not a Windows BMP file
15-02-13 10:07:21 AM	mcedit[643]	mcedit Error
15-02-13 10:07:21 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[649]) Bug: launchd_core_logic.c:4139 (24498):13
15-02-13 10:07:21 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[649]) posix_spawn("/Applications/Akamai/loader.pl", ...): No such file or directory
15-02-13 10:07:21 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[649]) Exited with exit code: 1
15-02-13 10:07:21 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist) Throttling respawn: Will start in 10 seconds
15-02-13 10:07:31 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[650]) Bug: launchd_core_logic.c:4139 (24498):13
15-02-13 10:07:31 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[650]) posix_spawn("/Applications/Akamai/loader.pl", ...): No such file or directory
15-02-13 10:07:31 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[650]) Exited with exit code: 1
15-02-13 10:07:31 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist) Throttling respawn: Will start in 10 seconds
15-02-13 10:07:41 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[651]) Bug: launchd_core_logic.c:4139 (24498):13
15-02-13 10:07:41 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[651]) posix_spawn("/Applications/Akamai/loader.pl", ...): No such file or directory
15-02-13 10:07:41 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[651]) Exited with exit code: 1
15-02-13 10:07:41 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist) Throttling respawn: Will start in 10 seconds
15-02-13 10:07:51 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[653]) Bug: launchd_core_logic.c:4139 (24498):13
15-02-13 10:07:51 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[653]) posix_spawn("/Applications/Akamai/loader.pl", ...): No such file or directory
15-02-13 10:07:51 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[653]) Exited with exit code: 1
15-02-13 10:07:51 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist) Throttling respawn: Will start in 10 seconds
15-02-13 10:08:01 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[654]) Bug: launchd_core_logic.c:4139 (24498):13
15-02-13 10:08:01 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[654]) posix_spawn("/Applications/Akamai/loader.pl", ...): No such file or directory
15-02-13 10:08:01 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist[654]) Exited with exit code: 1
15-02-13 10:08:01 AM	com.apple.launchd.peruser.501[101]	(com.akamai.client.plist) Throttling respawn: Will start in 10 seconds

**Comment by Khroki** [comment] 2015-02-13 17:49
The problem is this line, it's not loading the splash properly. 

15-02-13 10:07:21 AM [0x0-0x34034].org.pythonmac.unspecified.mcedit[643] pygame.error: File is not a Windows BMP file.

A fallback has been added for the next release, so it won't crash. For now 1.2.4.0 should work.

**Comment by CoWinkKeyDinkInc** [comment] 2015-02-13 20:28
Do you know why does the icon switch to that python controller for half a second?

**Comment by Podshot** [comment] 2015-02-14 00:26
What do you mean by 'python controller'?

**Comment by CoWinkKeyDinkInc** [comment] 2015-02-14 01:25
The icon in the dock switches to a python holding the controller for a short while before turning back to normal.  This was present in the original MCEdit as well.  Could this be fixed?

**Comment by Podshot** [comment] 2015-02-14 01:34
Could you send us a picture of this icon?

**Comment by CoWinkKeyDinkInc** [comment] 2015-02-14 02:23
![f](https://cloud.githubusercontent.com/assets/7586568/6198272/cd8c13e8-b3b5-11e4-88a9-4815117035de.png)
Turns into this icon.

**Comment by Podshot** [comment] 2015-02-16 14:16
After some research, that icon is PyGame's icon. It will appear like that until PyGame loads our icon file.

**Comment by Khroki** [comment] 2015-02-17 16:41
Yeah, it flashes that before loading mcedit's icon. Let us know if it's fixed with the latest release.

**Comment by Khroki** [comment] 2015-02-24 02:15
Assuming fixed. Reopen if it isn't.

**Closed by Khroki** 2015-02-24 02:15 UTC
