### ISSUE TITLE
Bug Todo List

### ISSUE THREAD

**Issue by kristomayo** [Khroki/MCEdit-Unified#499] opened 2015-09-12 14:19 UTC
Okay, so here are 4 small bugs (and 2 big bugs + 1 crash bug) that I've found in the latest (1.4.0.1) version of MCEdit Unified.

1: Lever model looks more like a torch and less like a lever.
2: Tall plant graphics look like leaves. (Side note: On MCEdit 2, the tall plant leaves look like unknowns, but this could be solved by the custom blocks thing, although I haven't tested it.)
3: Sign graphics are incorrect.
4: Stairs z-fighting. Also, did I mention that the lighting is a bit far from Minecraft's?
5 (and this is a big one): Tile entities' contents cannot be viewed unlike in older MCEdit releases.
6 (and this is another big one): Double-clicking on a schematic file to open MCEdit no longer works properly, as it requires the item files. (Does it work with older releases of MCEdit?)
7 (and this was the crashy one): At least on my 16x16 chunk world, selecting a chunk beyond the chunk boundary crashes MCEdit with a "TypeError: 'NoneType' object is not iterable" error.

Those are what I could find in MCEdit Unified. Fix them please, especially 5 and 6?
From, kristomayo

**Comment by naor2013** [comment] 2015-09-12 14:25
6 is already fixed for next release
Can you explain 3, 4 and 5 a bit more?
Thanks

**Comment by kristomayo** [comment] 2015-09-12 14:31
You mean that 6 is already fixed in 1.4.0.2?
Alright, here's the more-explained versions of 3, 4, and 5.
3: The sign graphics display the sign as a full block, not as a full sign, and it just looks wrong.
4: The stair bottom model and the stair side model's textures z-fight with each other because there are two textures in the same spot that cause the z-fighting.
5: When you mouse-over the tile entities, it no longer shows the content of the tile entity like it did in the older pre-unified MCEdit releases.
Hopefully that helps you.

**Comment by naor2013** [comment] 2015-09-12 15:07
You need to click alt while hovering over tile entities to see more info. Not sure how it was before but I'm sure it's not a bug but on purpose like that now

**Comment by naor2013** [comment] 2015-09-12 15:09
I don't think clicking schematics to open MCEdit was ever a thing..
I will add it to our to-do list but I doubt we'll add that feature soon

**Comment by kristomayo** [comment] 2015-09-12 15:21
Ohh! Well, why not just say "Press ALT to view contents"? Also, I thought MCEdit worked if you set the schematic to open MCEdit. Are there any old releases of MCEdit that I can test with?

**Comment by Khroki** [comment] 2015-12-26 05:32
1. Lever model was me trying to make them look more passable than a cube with a tiny texture, it's on purpose because I'm not an opengl wizard.
2. Also on purpose because the plant tops change dynamically based on the block below them, and I not being good at opengl did it that way as a generic catch all graphic, whoever added the door model may want to look at it.
3. Standing signs are like that for the same reason as 1. I managed to give wall signs a terrible 2d model though. Need an opengl guy who wants to touch our mess of a renderer.
4. Never noticed this, might be a system specific bug but wouldn't surprise me if it wasn't.
5. Yeah, requires alt, just like any other block that is the view block info button, there are old releases in my mcedit-old repo if you really want to compare, but we're not changing this.
6. Should be fixed.
7. Should be fixed. Post an error if it isn't.

Closing this, if you want you can make a new issue for graphical issues, reopen if 6 or 7 isn't fixed in 1.5.0.0.

**Closed by Khroki** 2015-12-26 05:32 UTC
Labels: Bug, Discussion
