### ISSUE TITLE
MCPE Broken on Linux Mint

### ISSUE THREAD

**Issue by bgbrandongomez** [Khroki/MCEdit-Unified#694] opened 2016-06-29 22:25 UTC
I have tried compiling mcpe leveldb from Mojang myself and a variety of other things to try to get leveldb support, but I am having trouble figuring out what debug symbol is missing. Here are some screenshots of the error messages (without modifications from the default installation).

This happens only on Pocket Edition worlds and happens on every Pocket Edition world.

If you need more info, I will be glad to provide it so I can work with Pocket Edition worlds.

![screenshot from 2016-06-29 17 53 31](https://cloud.githubusercontent.com/assets/6305346/16470761/17d90e64-3e26-11e6-884c-62fd4b67865a.png)
![screenshot from 2016-06-29 18 17 01](https://cloud.githubusercontent.com/assets/6305346/16470762/17fc65b2-3e26-11e6-8a38-36dc3c1bdacf.png)

**Comment by LaChal** [comment] 2016-06-30 18:36
Indeed, if the packaged version of the PE support fails the tests during installation, local compilation is needed.

What is the version of your OS?
How did you try to recompile the PE support?

**Comment by bgbrandongomez** [comment] 2016-07-01 01:40
## OS Version (by cat /etc/*-release)
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"


## Recompilation Attempts
* I had tried to recompile the pe support by first using the commands from the .run installer (MCEdit.v1.5.3.0.Lin.Universal.run).

* I had also compiled and copied the leveldb files into mcedit pocket edition folder where the other version of the library was from the repository (https://github.com/Mojang/leveldb-mcpe).

* I also retried those commands from the installer, but by running setup.py and setupnx.py directly.

**Comment by LaChal** [comment] 2016-07-02 10:20
The error I see in the first screenshot seem to be related to you version of zlib.
The one needed to comile PE support is, idealy, zlib.so.1.2.8.

Also, if you used the latest Mojang's library version, this may be the cause.

I also remarked that the script `setupnx.py` was broken since the reference to the needed Mojang's library version has been removed from here. It is fixed now. If you want to use this file, please get the latest version here: https://raw.githubusercontent.com/Khroki/MCEdit-Unified/master/leveldb_mcpe/setupnx.py

The `setupnx.py` will check for binary dependencies, download and build the needed version of Boost (without changing the one you have, if any) and download and build Mojang's needed library version, create symlinks, put the stuff were needed and build and link PE support for MCEdit.

If you want to build manually, you'll need to download Mojang's library from here:
https://codeload.github.com/Mojang/leveldb-mcpe/zip/a056ea7c18dfd7b806d6d693726ce79d75543904

Read also the `LINUX_INSTALL.txt` file in MCEdit folder, especially the `POCKET EDITION SUPPORT COMPILATION` section.

**Comment by LaChal** [comment] 2016-07-06 19:18
@bgbrandongomez 
Any news on your side?

**Comment by LaChal** [comment] 2016-07-06 23:38
@bgbrandongomez 

I'll give a try on Mint 17.2 (only tested on 'fresh' Mint 17.1 for now, and all was OK...), but I need to know which flavor you've installed.
According to the download page (https://www.linuxmint.com/release.php?id=25) there are several environments available. Not surprising with Linux, but I need to know which one you're using to debug :smile:

**Comment by bgbrandongomez** [comment] 2016-07-09 13:57
@LaChal 

It is Cinnamon 64-bit.

Thank you for helping me test this to help me fix it. I really appreciate it!

----------------------------------------
cat /etc/linuxmint/info
----------------------------------------
RELEASE=17.2
CODENAME=rafaela
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17.2 Rafaela"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rafaela_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rafaela_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.2 Cinnamon 64-bit

**Comment by LaChal** [comment] 2016-07-11 20:02
I finally found room on my machine (and time) to install a Mint 17.2 VM.
The file `/etc/linuxmint/info` gives me the same information as yours.

Except some OpenGL errors (because I'm on a VM), all is good on may side with the PE support. The test performed during installation were OK...

I see I was wrong in one of my post concerning zlib. The .so shall be **libz**.so.1.2.8 (in `/lib/x86_64-linux-gnu/`). As I said, this is the ideal version.
Can you check which version of this library you have on your system, please? (A `find / | grep libz` command in a root shell may help :wink:)

Another question: did you try to download and run again the installer?

**Comment by ZephaniahNoah** [comment] 2016-07-21 01:33
Same problem in Ubuntu. 
![mcedit](https://cloud.githubusercontent.com/assets/14168013/17008651/e8244eb2-4e8e-11e6-9965-52999ac758d5.png)
![mcedit2](https://cloud.githubusercontent.com/assets/14168013/17008678/335cec5e-4e8f-11e6-9270-c27a2d44758e.png)

**Comment by LaChal** [comment] 2016-07-21 05:59
Nope, different problem here.

Looks like a file is missing.

What is the version of your OS?
What says the console when running MCEdit?
Which files do you have in the folder `~/.local/lib/leveldb-mcpe`?

**Comment by bgbrandongomez** [comment] 2016-07-24 19:50
@LaChal 

I had switched over to Kali Linux as I am going off to college. I appreciate the support you have given me and maybe this will help other people runnning Linux Mint.

Thank you,
Brandon Gomez

**Comment by LaChal** [comment] 2016-07-24 20:30
Kali is Debian based, so MCEdit intaller may work.

Any feed back will be appreciated :smile:

**Comment by ZephaniahNoah** [comment] 2016-08-02 21:22
@LaChal I am running Xubuntu 16.10 which I believe is Debian based.
leveldb-mcpe has libleveldb.so libleveldb.so.1 and libleveldb.so.1.18

**Comment by LaChal** [comment] 2016-08-02 22:46
@ZephaniahNoah : do you have a `~/.local/lib/leveldb-mcpe` directory?
If yes, are the three files in?

**Comment by bgbrandongomez** [comment] 2016-08-03 13:38
Hello, as for me, the installer does not want to cooperate with me on Kali Linux, however, I have become busy so I will probably have to open up a new issue when I do get time to debug it. Thank you for your help.

**Comment by ZephaniahNoah** [comment] 2016-08-04 19:16
@LaChal Yes I have that directory and those are the three files that are in it. I won't be able to continue this though because my computer just died. If I ever get it working I'll let you know. :(

**Comment by LaChal** [comment] 2016-08-04 20:09
Sad new...

Feedback is welcome, of course!

**Closed** 2016-08-04 20:12 UTC
Labels: LevelDB Format, Linux
