### ISSUE TITLE
Error reading chunk: NBT Stream too short.

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#473] opened 2015-08-15 21:17 UTC
I opened this 0.11 PE world: https://www.dropbox.com/sh/gwyvhwj79axr5zi/AACcwOPc-0CK7Y7_K0-qdUUFa?dl=0
And I get these errors as I fly arround:
http://pastebin.com/PQAAfJjm

**Comment by Khroki** [comment] 2015-09-05 15:12
Anyone tested this?

**Comment by Khroki** [comment] 2016-02-02 20:09
Closing this as a duplicate of https://github.com/Khroki/MCEdit-Unified/issues/568 We will post further updates there. Thanks for the world though.

**Closed by Khroki** 2016-02-02 20:09 UTC
Labels: Bug, Pocket Version
