### ISSUE TITLE
Pocket world Shadows - 1.5.3.0 & earlier

### ISSUE THREAD

**Issue by Robbeedee** [Khroki/MCEdit-Unified#671] opened 2016-05-20 10:20 UTC
Hi there,

I have had this problem since I started trying to use MCEdit, which has obviously made it unusable because it is a world destroyer. 

Once a map has been edited, the chunk will become filled with these extremely dark shadows as soon as you interact with it. Either adding or removing blocks will do it. The more you do to the chunk, the more the shadow spreads.

Here I opened a basic world, added a few structures in MCEdit, and then sent it back to the iPhone for testing.

![img_4084](https://cloud.githubusercontent.com/assets/18512897/15424824/440cb7e4-1eb7-11e6-97dc-812493942cbb.jpg)
![img_4087](https://cloud.githubusercontent.com/assets/18512897/15424827/476502a2-1eb7-11e6-8475-6a2a158cf774.jpg)

Cheers!

**Comment by Khroki** [comment] 2016-05-21 15:50
Does adding a light source to the affected chunk(s) reloading help? Either via pocket or MCEdit.

**Comment by Robbeedee** [comment] 2016-05-23 00:00
Hi Khroki,

Adding a light source lights up the surrounding areas in the typical light source fashion. It acts like a light inside a dark cave, rather than recalculating the lighting for the area.

![img_4119](https://cloud.githubusercontent.com/assets/18512897/15457488/5b4d1c1c-20bc-11e6-9fa6-b11702701eb1.jpg)

**Comment by Khroki** [comment] 2016-05-23 01:43
That's strange, it almost looks like there is a block of some sort at the top of the world blocking the sun.

**Comment by Robbeedee** [comment] 2016-05-23 07:17
Here is some video in case the behaviour helps you to identify the problem.

https://www.youtube.com/watch?v=Lq-8N_ZX25U

**Comment by Khroki** [comment] 2016-05-27 04:18
Confirmed, looks like an issue with how sun lighting is handled. We'll get to it when we can.

**Comment by builddroid** [comment] 2016-06-04 03:44
I've used other world editing tools on MCPE worlds and get the same result - adding or removing large numbers of blocks causes this shadow issue. These are Android apps I have used, and the issue only started with the 0.14 update.

**Comment by LaChal** [comment] 2017-06-12 19:18
@Robbeedee, @builddroid: I'm closing this issue now, because it has not been updated since a year.
We alos have worked on a new PE support, and Mojang changed the PE world format. (Lights were stored in the world, but in PE 1.1, they're calculated on-the-fly).

Note that, this new PE support is availble only if you run MCEdit from source for now; and using the 'new feature' stuff described [here](https://github.com/Khroki/MCEdit-Unified/issues/779#issuecomment-288840904).
The new support will be the default one in the next release :smile:

**Closed by LaChal** 2017-06-12 19:18 UTC
Labels: Bug, LevelDB Format, Medium
