### ISSUE TITLE
Crashes when Opening SunBurn 0.5

### ISSUE THREAD

**Issue by yrsegal** [Khroki/MCEdit-Unified#278] opened 2015-01-21 02:01 UTC
```
1/20/15 8:58:53.000 PM kernel[0]: Sandbox: mcedit(5243) System Policy: deny file-write-unlink /Users/yoni/Library/Saved Application State/org.pythonmac.unspecified.mcedit.savedState/restorecount.plist
1/20/15 8:58:53.544 PM mcedit[5243]: [   ERROR][                   root.py:710]:MCEdit version Unified v1.2.5.0 for Minecraft 1.8
1/20/15 8:58:53.546 PM mcedit[5243]: Traceback (most recent call last):
1/20/15 8:58:53.546 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 399, in <module>
1/20/15 8:58:53.546 PM mcedit[5243]:     _run()
1/20/15 8:58:53.546 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/__boot__.py", line 336, in _run
1/20/15 8:58:53.546 PM mcedit[5243]:     exec(compile(source, path, 'exec'), globals(), globals())
1/20/15 8:58:53.546 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 748, in <module>
1/20/15 8:58:53.546 PM mcedit[5243]:     sys.exit(main(sys.argv))
1/20/15 8:58:53.547 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 708, in main
1/20/15 8:58:53.547 PM mcedit[5243]:     MCEdit.main()
1/20/15 8:58:53.547 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/mcedit.py", line 544, in main
1/20/15 8:58:53.547 PM mcedit[5243]:     rootwidget.run()
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/root.pyc", line 125, in run
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/root.pyc", line 191, in run_modal
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/widget.pyc", line 734, in gl_draw_all
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/widget.pyc", line 734, in gl_draw_all
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/widget.pyc", line 734, in gl_draw_all
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/widget.pyc", line 734, in gl_draw_all
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/widget.pyc", line 731, in gl_draw_all
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/openglwidgets.pyc", line 22, in gl_draw_self
1/20/15 8:58:53.547 PM mcedit[5243]:   File "albow/openglwidgets.pyc", line 28, in gl_draw_viewport
1/20/15 8:58:53.548 PM mcedit[5243]:   File "viewports/camera.pyc", line 1333, in gl_draw
1/20/15 8:58:53.548 PM mcedit[5243]:   File "viewports/camera.pyc", line 1348, in render
1/20/15 8:58:53.548 PM mcedit[5243]:   File "renderer.pyc", line 2993, in draw
1/20/15 8:58:53.548 PM mcedit[5243]:   File "glutils.pyc", line 198, in bind
1/20/15 8:58:53.548 PM mcedit[5243]:   File "/Users/yoni/Downloads/mcedit.app/Contents/Resources/lib/python2.7/OpenGL/error.py", line 232, in glCheckError
1/20/15 8:58:53.548 PM mcedit[5243]:     baseOperation = baseOperation,
1/20/15 8:58:53.548 PM mcedit[5243]: OpenGL.error.GLError: GLError(
1/20/15 8:58:53.548 PM mcedit[5243]: 	err = 1282,
1/20/15 8:58:53.548 PM mcedit[5243]: 	description = 'invalid operation',
1/20/15 8:58:53.548 PM mcedit[5243]: 	baseOperation = glBindTexture,
1/20/15 8:58:53.548 PM mcedit[5243]: 	cArguments = (GL_TEXTURE_2D, 3L)
1/20/15 8:58:53.548 PM mcedit[5243]: )
1/20/15 8:58:53.599 PM mcedit[5243]: mcedit Error
1/20/15 8:58:53.599 PM mcedit[5243]: 2015-01-20 20:58:53.599 mcedit[5243:162446] mcedit Error
```

I don't even know. Help, please? http://www.curse.com/worlds/minecraft/224450-sunburn-burn-or-be-burned/ for the world download.

**Comment by Podshot** [comment] 2015-01-21 02:12
From just a quick glance, is your antivirus running it in a sandbox mode?

**Comment by yrsegal** [comment] 2015-01-21 02:21
ehm... I don't use antivirus on my mac
I can probably sudo it if needed

**Comment by yrsegal** [comment] 2015-01-21 02:23
Thing is, it works with any other world. Just sunburn is weird. Try running this on your computer, see what you get.

**Comment by yrsegal** [comment] 2015-01-21 02:26
Ah, I have it. Wither Skull entities break the renderer for some reason; opened up a bunch of worlds to check, this is 100% true.

**Comment by martinhanzik** [comment] 2015-01-21 10:20
Well this is the same error, that was happening when using the wrong tab in finder when opening files, it only worked with the second one. Which tab were you using?

**Comment by Khroki** [comment] 2015-01-23 14:01
That's odd, if a part of the renderer is broken it doesn't crash, it just doesn't show that chunk. Also wither skulls are defined identically to the other skulls, unless mcedit's skull editor is trying to load a name field where there isn't one.

**Comment by Podshot** [comment] 2015-01-23 15:09
Wither Skulls are entiies and cannot be edited withthe Skull Editor, I have a few worlds with Wither Skulls to test this with

**Comment by Khroki** [comment] 2015-01-28 15:57
Closing this as a duplicate of https://github.com/Khroki/MCEdit-Unified/issues/259 and https://github.com/Khroki/MCEdit-Unified/issues/257, if you find more info post in one of those.

**Closed by Khroki** 2015-01-28 15:57 UTC
Labels: Crash, OS X, System Specific
