### ISSUE TITLE
MCEdit Won't Stay open

### ISSUE THREAD

**Issue by rockydog92** [Khroki/MCEdit-Unified#535] opened 2015-11-25 17:21 UTC
I start up MCEdit but it either closes or doesn't respond and sometimes when it goes to the splash screen it will have the image but when I look at task manager it says it's not running or not responding.
Here is one of the logs (It's the only one I could find)

[mcedit.txt](https://github.com/Khroki/MCEdit-Unified/files/44127/mcedit.txt)

**Comment by LaChal** [comment] 2015-11-25 20:41
The log is quite short...

Did you try to reinstall MCEdit?

**Comment by rockydog92** [comment] 2015-11-26 00:10
Yes I did, the log is only from the command prompt, it had an **error** *(apparently :( )* and it only was able to load the "Splash Screen".

**Comment by robske110** [comment] 2015-11-26 05:44
I do have that issue too, but only in my VirtualBox (with Windows). The problem there is, that a openGL function is not in the graphic driver.
Try to update your graphic driver... And what graphic card do you use (CPU-graphics/Nvidia/Amd/etc)

**Comment by robske110** [comment] 2015-11-26 05:45
Oh, I forgot to mention, that mcedit 2.0 works in my virtual box (Does it rely on opengl?)

**Comment by LaChal** [comment] 2015-11-26 07:24
What said robske110 about the grapics driver had been my next suggestion...

The error we see in the log is related to an internal file which can't be found, but MCEdit starts using a fallback. (This file is used to speed up the program.)

Don't you have a `mcedit.log` file in your MCEdit folder?

**Comment by rockydog92** [comment] 2015-11-26 22:56
I cannot really find all the info on my graphics card but all I really know is that it’s Intel HD Graphics. 
(What’s a VirtualBox?, also I will comment in a little bit after I make this comment with the full specs after I check something else to see if there are updates available for it.  I’m also running Windows 10 on a Dell - originally Windows 8 then 8.1)

**Comment by rockydog92** [comment] 2015-11-26 23:00
Intel® HD Graphics 4000
It was up to date, I think I have to many files from MCEdit on my computer, because I’m pretty sure I found multiple files for it.  Do you want me to delete all those files and try downloading MCEdit again?

**Comment by rockydog92** [comment] 2015-11-26 23:02
I don’t really know can you explain to me what OpenGL is?  The internet kinda failed at telling me what it is.

**Comment by rockydog92** [comment] 2015-11-26 23:04
I will check, also I think I found multiple MCEdit files, I’m pretty sure I have downloaded it more than once, do you want me to try and find all those files and delete them?  I will reply a few minutes after this comment so I can check.

**Comment by rockydog92** [comment] 2015-11-26 23:26
My downloads folder is where all these files are because that’s where I opened it and it decided to leave all it’s files all strewn all over the place, but I searched my downloads folder  for the “mcedit.log” file, but I only found the one I previously posted.  I also downloaded mcedit again and it said it’s files where  going to be put in “System32” so I’m searching my “OS C” drive and It appears I found another group of MCEdit files in another one of my folders.  I will try to start it from there and get back to you in a few minutes.

**Comment by rockydog92** [comment] 2015-11-26 23:41
AMAZING NEWS EVERYONE!!!, after I searched my computer for *mcedit.log*, I found there was another folder I had forgotten about that had MCEdit in it!!  I loaded it up and it worked!! I'm gonna attach the *mcedit.log* file just cause.  But before we can close this issue I'm going to update MCEdit (It said there was an update available) so hold tight!!!  

[mcedit.txt](https://github.com/Khroki/MCEdit-Unified/files/45321/mcedit.txt)
I'm gonna start MCEdit back up and update it, I'll tell you the details in a few minutes!!!

**Comment by rockydog92** [comment] 2015-11-26 23:46
I downloaded the update, where do I need to extract the file to? where I have the MCEdit files and tell it to replace any files with the same name and all that in that destination? Or where? Please Help!!

**Comment by LaChal** [comment] 2015-11-27 07:07
A VirtualBox is a virtual computer. It is used when one need a specific OS to run.
OpenGL is a video library/driver: https://www.opengl.org/ https://en.wikipedia.org/wiki/OpenGL.

If the update you're talking about is the latest version of MCEdit, you can overwrite your actual install, or put it in another folder.
The second option is better, because you'll have a clean install.

**Comment by robske110** [comment] 2015-11-27 12:44
@LaChal Explained everything.
And one question how do you tag or close an issue?

**Comment by rockydog92** [comment] 2015-11-27 15:42
I’ll do that, but where do I extract the update to?

**Comment by robske110** [comment] 2015-11-27 15:45
I would say anywhere you want, i would prefer the desktop!

**Comment by rockydog92** [comment] 2015-11-27 17:02
Thanks, I’ll do that then close this thread, after tI make sure the extraction worked!!

**Comment by LaChal** [comment] 2015-11-27 18:52
@robske110: only some people can close issues. Typicaly the its creator and project contributors.

**Comment by robske110** [comment] 2015-11-27 19:48
@LaChal Thanks, I am new to GitHub...
Back to the issue is it fixed now?

**Comment by LaChal** [comment] 2015-11-27 20:10
@robske110: waiting for @rockydog92...

**Comment by rockydog92** [comment] 2015-11-27 22:58
I still have to extract it, I’ll have it done by tomorrow.

**Comment by rockydog92** [comment] 2015-11-29 00:47
I don't know what happened, but I extracted the update to the folder that has MCEdit in it, thinking that it would replace any files with the same name.  But when I went to that folder and started MCEdit up it still came up and said there was an update available.  I will try to extract the update to the folder again after I delete all the files for MCEdit currently in it.

**Comment by rockydog92** [comment] 2015-11-29 00:55
Ok, I did that, and it worked!!!  
Thanks, 
@LaChal 
and 
@robske110 !!!!
After you guys post any closing remarks, I'll close the issue!!

**Comment by LaChal** [comment] 2015-11-29 10:15
Done.

**Closed by LaChal** 2015-11-29 10:15 UTC

**Comment by rockydog92** [comment] 2015-11-29 16:26
Thanks For Your Help!!!
