### ISSUE TITLE
Support MCPE Leveldb worlds

### ISSUE THREAD

**Issue by L3ice** [Khroki/MCEdit-Unified#131] opened 2014-11-03 12:57 UTC
I want to port MCPE worlds but I cant.
Please update it with the new leveldb format!

https://github.com/Mojang/leveldb-mcpe

**Comment by MobileCrafter** [comment] 2015-01-03 23:17
So will it now be implemented?

**Comment by Joeschmoh** [comment] 2015-02-21 19:07
This thread hasn't seen an action in a while, any progress on this? 

I'm an old enough dinosaur to be fluent in C, I have worked with python before, and I have kids that play MCPE who want this to work.

It sounds like what you are asking for is a Windows port of the Mojang LevelDB library so you can call it from Python? That sounds plausible, but I'd need more information on exactly what is needed. 

Anyway, PM me if are interested.

**Comment by Khroki** [comment] 2015-02-22 14:04
Github doesn't have a PM system anymore, so I'll respond here. basically mojang's LevelDB is already Windows compatible, the issue is we don't have a python library/wrapper to read it, as all the preexisting ones are for the non-mojang version. And without the knowledge of both C and Python, we don't have anyone who can make one.

**Comment by naor2013** [comment] 2015-02-22 14:05
Actually, C++

**Comment by Khroki** [comment] 2015-02-22 14:05
Fine C++ then :P

**Comment by Joeschmoh** [comment] 2015-02-22 15:54
Okay, I've done most of my programming in C/C++. I've worked with Python before, can't say I'm fluent but probably have enough skills there. I'm willing to help, in any event. I guess the next big question is where to get started.

**Comment by naor2013** [comment] 2015-02-22 15:57
We need the leveldb system to work with Python to allow us to get to the files and read them correctly so we need the link below to work in Python:
https://github.com/Mojang/leveldb-mcpe

**Comment by Joeschmoh** [comment] 2015-02-22 22:44
Okay, let me dig into this. I have a better idea of what is needed. Looking over the link above, I'm guessing we will want to build their LevelDB interface into a DLL (if it doesn't build that way already) that we can then write some python wrapper code around to act as a glue layer between MCEdit and LevelDB. 

My initial guess is that memory management *might* be trickiest part. But there seem to be a lot of examples on how to handle this (i.e. I googled it). Also, we'll have to consider if Mojang makes different versions of LevelDB that aren't backwards compatible. And finally, if you are just using Python I'm guessing adding in a C++ component means a big change to your build process.  

I'm saying this just looking over docs and stuff, obviously I need to actually check out code and see how this all fits together.

**Comment by Khroki** [comment] 2015-02-23 04:28
Currently the build process doesn't have any C or C++ compiling at all, Windows is built using Pyinstaller, Mac with Py2App, and linux essentially runs from source. Seeing as all 3 are different, having to build any C or C++ code may affect our build capabilities, especially with the sensitivity of the Mac environment. So something that directly interfaces or can be pre-compiled for inclusion in the repo (like our NBT library) would be ideal. Not sure if a DLL would work for the unix-based OSes.

**Comment by OniOniOn-** [comment] 2015-03-04 16:52
Hello? Answer would be nice!

**Comment by LaChal** [comment] 2015-03-04 21:06
DLLs won't work on Linux/OSX systems*.
Moreover, on Linux, you can't just download a dynamic library and have it work. It can work, but it depends on the specific distribution. (Mainly kernel and system libraries versions). So, the source code have to be recompiled on Linux machines.
And the code written on Windows uses Windows specific dependencies. It won't compile on Linux or OSX as-is, modifications have to be made...

The most 'simpliest'** and effective solution is to have system independent code.

FYI, Python is built over C.


----------------------------------------------------
* There are some emulators/interfaces to run Windows programs on Linux. But those solutions are tricky to use and configure, and some are expensive. And most of users won't mess with VMs or deep in Wine settings to run a sole program (even wteher Wine is a very good stuff :) )...

** Porting from a language to another can be hard, very hard. But once done, only one code source is maintained, with some tweaks to fit the target system. This is what we do with MCEdit...

**Comment by Joeschmoh** [comment] 2015-03-05 02:48
I've been looking through this. One of the challenges is I can't find any Mojang specific build instructions for the LevelDB code. Sure there is a Makefile and a dependency script, but that alone doesn't answer a lot of the questions on building C/C++ objects. So that'll take time for me to try various combinations and get it to build on each platform.

I'm making an assumption here, but the code is supposed to allow building as a DLL on Windows. I can't see any documentation for how it builds on Linux, but it looks like a static library (the "Linux" support is there, but mostly its written to support Android from what I can tell). Usually, though it's not to hard to make a static library into a ".so" or shared object on Linux. That would be the Linux equivalent of a DLL. Mac is a different beast, with any luck the Linux code will largely build on Mac (but that said, I don't have a Mac to test with). 

Based on LaChal's comments, are you suggesting re-writing the C/C++ LevelDB code in Python? That would certainly make it more portable, but that is a LOT of work! But this does beg the question of exactly what are you hoping in the final product here? 

As I see it, there are two solutions -- 
 *  The quickest solution is building the LevelDB as is into shared libraries (DLL or .so), and then creating a Python "glue" layer to interface into the library. It appears Boost.Python may have an answer for the glue layer portion too -- http://www.boost.org/doc/libs/1_36_0/libs/python/doc/index.html. This does mean shipping the library with MCEdit -- it could be handled by having people download the library if they desire it and the MCEdit code uses it if its available.
 *  The other solution is a Python re-write of the C++ libraries, which will take much longer to do but obviously is the most seamless implementation. I'll be honest that I'm not quite sure I'm able to devote enough time to deliver something like that.

Either way, it's an important question -- what is the desired outcome?

**Comment by LaChal** [comment] 2015-03-05 07:35
An other solution is to use Python.h in the code source and write the Python itenrface in the library to obtain a .pyd object.

The interface to use is described in the Python documentation, in the 'Extending and Embedding' and 'Python/C API' topics (see https://docs.python.org/2.7/).

**Comment by Khroki** [comment] 2015-03-06 04:13
Well, the second solution would be cleaner, but anything you want to do is better than it is now, only thing is compiled builds can't really use external libraries, only the ones specified at build time, so we would have to include it in all win/mac builds. Not a huge issue assuming compatibility is there. Also Mac isn't compatible with .so files as far as I'm aware.
Also LaChal's may work too, up to you really.

**Comment by TrazLander** [comment] 2015-04-08 03:05
You look into this anymore @Joeschmoh? More people always asking us for this:
http://www.reddit.com/r/MCEdit/comments/31rdda/support_for_minecraft_pocket_edition_please/

**Comment by Bananamon** [comment] 2015-04-08 14:01
I was told to bug you guys here. Lol :smile: 

I think MCPE support is overdue. There are millions of people who would love to be able to edit their maps. I used to love MCEdit till 0.8.x update, till when it was possible. 

I hope you guys will implement support for it ASAP. :+1:

**Comment by Joeschmoh** [comment] 2015-04-08 15:04
This is still on my agenda! I apologize for not having anything yet, I'm behind where I wanted to be and I'll blame my work. I promised this at a time my job suddenly got really busy. I hear the message, and I want MCPE support too! I have 3 kids bugging me for it.

**Comment by Bananamon** [comment] 2015-04-10 06:24
@Joeschmoh listen to your kids! :stuck_out_tongue_closed_eyes:

**Comment by MobileCrafter** [comment] 2015-05-04 13:57
@Joeschmoh Any news?

**Comment by Bananamon** [comment] 2015-05-10 13:56
**PING**

**Comment by Bananamon** [comment] 2015-05-10 13:59
I know I am spamming and I am sorry for that but MCPE support has been overdue. It's been almost 1.5 years since 0.9.0 update came out which introduced infinite worlds. We are missing out on too much

**Comment by Rubisk** [comment] 2015-05-21 21:48
I started work! Sort of. Took me 3 days to compile mojangs leveldb and get boost setup, I just started wrinting the wrapper. After that's done we should be able to start working on the actual code. It's a long way...

**Comment by Bananamon** [comment] 2015-06-02 11:33
YAAAAAAAAAAAAAAAYYYYYYYYYYYYY!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :+1: :smile:

**Comment by Rubisk** [comment] 2015-06-02 11:38
It basically all works. We now just need to build it, and get the bugs out :/

**Comment by shoghicp** [comment] 2015-06-03 07:50
@Rubisk
Hey! I saw you connect the #mcpedevs channel over freenode and ask about leveldb there, but you disconnected.

MCPE only uses the custom zlib compressor on leveldb, so snappy is not needed (although you can support is as well, maybe other tools use it!)
Besides the wiki documentation, I've some code over the PocketMine repository (src/pocketmine/level/format/leveldb), that can help you with more information if you need it as well.

**Comment by Rubisk** [comment] 2015-06-08 19:51
Thanks a lot, that makes me feel a lot safer ^^

**Comment by Khroki** [comment] 2015-06-17 14:30
Onionion, and anyone else interested in pocket, we need the pocket.yaml updated with all new blocks, could someone do that and submit a pull request?

**Comment by OniOniOn-** [comment] 2015-06-17 15:54
@Khroki I also don't have one, but I will try to get it updated until weekends over...

**Comment by Khroki** [comment] 2015-06-17 16:10
It's fine if you don't, Naor is going to look into it tomorrow.

**Comment by OniOniOn-** [comment] 2015-06-18 14:34
Alright, I think this will be good opportunity to use same texture as PC one.

**Comment by OniOniOn-** [comment] 2015-06-18 15:12
Tell me where MCPE is needed and I will find someone to help with that...(if still needed)

**Comment by TrazLander** [comment] 2015-07-08 10:52
Closing this as MCPE world support is pretty much done. From now on every issue and error related to this can be it's own individual report.

Also, WOO

**Comment by Rubisk** [comment] 2015-07-21 19:21
Were having some trouble moving players around.

I can't test myself, but according to @naor2012 players dont get theit position saved correctly. I can't remember if we were able to edit other player data, up to @naor2012 to test that.

Mcedit loads the pos correctly on restart, but phones tp the player to 0, 0, 0. Were saving it as a List of Doubles,  named "Pos" under ~local_player. Also calling to @shoghicp for sone help?

**Comment by Rubisk** [comment] 2015-07-21 19:22
@naor2013, I meant to call you instead.

**Comment by OniOniOn-** [comment] 2015-07-22 05:09
Almost nobody use it anyway

**Comment by naor2013** [comment] 2015-09-05 18:40
There is more stuff to do to make it perfect (Some are listed here: https://github.com/Khroki/MCEdit-Unified/issues/457 ) but this feature is mostly done, so I'm closing this issue!
Thanks for everyone who helped

**Closed by naor2013** 2015-09-05 18:40 UTC
Labels: Looking for Help, Medium, Pocket Version
