### ISSUE TITLE
Don't mess with the session lock.

### ISSUE THREAD

**Issue by codewarrior0** [Khroki/MCEdit-Unified#328] opened 2015-03-08 14:26 UTC
I noticed somebody inserting "level.acquireSessionLock()" in various places in an attempt to forcibly retake the session lock.

Don't do that. Seriously. 

The session lock exists to keep the world folder in a consistent state. When you lose the session lock, any data you cached from the world file is no longer usable, and trying to use that data will result in a corrupt world.

When Minecraft loads a world that is open in MCEdit, several things happen. First, MCEdit's internal chunk cache (MCInfdevOldLevel._loadedChunkData and .unsavedWorkFolder) is no longer consistent with the chunks on disk. If MCEdit tries to reacquire the lock and write the cached chunks out, the resulting world file won't be consistent with what the user had just seen in *either Minecraft or MCEdit.*  

Secondly, the cached level.dat and player.dats will not be consistent. MCEdit will write out its cached level.dat when the world is saved, and things like player position and inventory, or more alarmingly the "in-game time" field will revert to their previous values. The in-game time is also stored in each chunk as the last update time, and it is probably not a good idea for chunks to have a last update time that's in the future.

Thirdly, and most importantly, MCEdit's region file cache is no longer consistent. If Minecraft reallocates a chunk, MCEdit won't know about it and will write it to its original position, possibly overwriting another chunk Minecraft had allocated there. This causes *serious damage to the region file*. When it is opened again, chunks will simply be missing. (This is the symptom of a problem I had way back in Minecraft Beta 1.4, when Minecraft would not unload its region file cache after quitting back to the title screen. This is why I had to show a warning to completely close Minecraft before using MCEdit.)

The only sane response to losing the session lock is to close the world (discarding all changes) and reload it. The most polite thing to do would be to, after reloading the world, replay the user's editing history since the last save. In effect, replaying all of his changes over the new state of the world as it is after Minecraft changed it.

**Comment by OniOniOn-** [comment] 2015-03-08 14:30
I will try not to do that!

**Comment by naor2013** [comment] 2015-03-08 14:31
We're using it for the Save As option and we try to make it able to kind of remember how's MCEdit is seeing the map and not how Minecraft changes it.
Can you give us some examples of steps to reproduce that can break it, so we could test them? It's still on a test stage and we'll revert it if it will be too broken

**Comment by codewarrior0** [comment] 2015-03-08 14:48
It doesn't matter that it's a Save As option. You won't need to reacquire the lock, since if you already have it, you'll be copying the session.lock file along with everything else. And if you don't have it, you need to fail before you even begin making a copy of the world. The way you wrote it, your "Save As" will ignore the lock file and write an inconsistent world to the new filename if the world was opened in Minecraft.

And @naor2103? You REALLY need to work on writing better commit messages.

**Comment by naor2013** [comment] 2015-03-08 14:52
Ok, so I'll write in a different way where when you open the world it will automatically copies the world and the Save As option will copy it from there where the Session lock isn't stolen yet

And the reason I sometime use names like "small changes" is because I don't want someone to accidentally think it's important and add it to the changes log but when it's important enough I use better names

**Comment by codewarrior0** [comment] 2015-03-08 15:02
Okay, first off. Every change is important. If it's not worth writing a good commit message for, don't even bother committing it. I'd say fixing a problem where your "Save as" actually overwrote the original world file before making a copy is *pretty fucking important*, not to mention messing with lock files! 

It's up to whoever is making the release builds to filter through the commit history and write a change log for the users. Don't make his job harder by writing "fixed a thing" and making him read through the diff to find out what you changed.

Making an entire copy of the world every time you load it is a possibility, and it would neatly sidestep any issues with the session lock being lost. Any changes made in Minecraft while MCEdit has the world loaded will be lost, of course. But you need to be prepared for people opening worlds of 500MB, 1GB or more, and making them wait that long just to open the world. And you can't leave anyone wondering whether it's "okay" to edit a world in two programs at once. (It's not and shouldn't ever be. I don't know why everyone keeps trying to do it.)

**Comment by Khroki** [comment] 2015-03-09 01:53
I'm the one who makes the change logs, and it's really not that big a deal tbh. the vast majority of the time I can figure out the change pretty quickly. The commits that are annoying are the ones so long you can't read them fully in the client, even that's not a huge deal.

Anyway, on session lock, I've never been a fan of lock swapping and think it's a bad idea unless it can be made safe, since it leaves a non-zero corruption chance which is more than I'm really willing to gamble personally. The reason people want it is so they don't have to spend the extra few seconds closing and opening worlds. So unless it can be made safe without adversely affecting performance and load times, I would keep it in the discouraged but not going to stop it camp. Meaning either we need to find a way around the corruption chance or remove the lock stuff for now.

**Comment by TrazLander** [comment] 2015-03-09 23:05
Most of that whole thing is an experiment for us newbs to see what's possible, what walls we run into, and see what can be fixed. People losing work due to accidentally losing the session lock either in mcedit or Minecraft has been an issue for a long time. Telling them to just deal with it and suck it up really isn't the best way, and ignoring it because you can't do anything about it isn't that great either. It's good to look into what can be done about it, even if it's a bumpy road on the way.

**Closed** 2015-03-09 23:07 UTC
Labels: High

**Comment by codewarrior0** [comment] 2015-03-10 00:16
It's great that you want to protect users from their own mistakes, but you can only go so far. No limits to human fallibility, after all. Losing work because you forgot to Save before going into Minecraft is something I've known about for a while, and I could have told you all about the problem and outlined several solutions if you asked. If you have any questions, I can be reached at codewarrior0@gmail.com

**Comment by Khroki** [comment] 2015-03-10 00:24
We were under the impression you didn't really want to get involved, that's why we haven't really messaged you (plus previous stuff to that email didn't get a response). We usually do most development discussion on Skype though.
