### ISSUE TITLE
Shops Filter

### ISSUE THREAD

**Issue by Azounstone** [Khroki/MCEdit-Unified#742] opened 2016-12-02 12:48 UTC
Hello,

When using the shops filter in 1.11 it no longer works. It does nothing when you run the filter.

Would you be able to fix this please?

Thanks,

Andy

**Comment by LaChal** [comment] 2016-12-07 20:20
Hmmm...

I don't experience this on my side.

It may look silly if you know how to use MCEdit (and the shop filter), but performing the following steps works for me:

1. Open a MC 1.11 world (non modded).
2. With the brush tool, place a chest.
3. Double click on the chest to edit its content, and add 3 items in the slots 0, 9, and 18.
4. Select the chest, or a zone containing the chest.
5. Open the `Create Shops` filter, set up the behaviour of the trader and apply the filter.
6. Save and close the world.
7. Open it in the game.
8. Trade.

When editing the chest content, I use the string IDs. I did not test the numeric ones.
If you have `minecraft:diamond` as ID for a slot, you'll see `Diamond` in the rightmost column.

Hope this will help :smile:

(If not, eh... need more info about how you're working with the filter...)

**Comment by Azounstone** [comment] 2016-12-07 21:52
Hello,

I place the chest in the world manually and add the contents just the same way I have done over 500 times previously (the real number will actually be higher than this) and after running the filter nothing happens. It stays as a chest.

I have never done it the way you say as you can not add coloured nbt items that way.

[mcedit.zip](https://github.com/Khroki/MCEdit-Unified/files/637842/mcedit.zip)

Please watch all of the video past the black screens and you will clearly see that running the filter does nothing.

Thanks,

Andy

**Comment by Azounstone** [comment] 2016-12-07 21:56
Please Note:

I have just done the exact same thing in a 1.10.2 world and it works just fine.

**Comment by LaChal** [comment] 2016-12-07 23:17
Thank you for the video.

I'll try to reproduce the bug.

Maybe something to do with the custom head or the orientation. (I did not test that in 1.11 on my side.)
But it may also be due to the fact you don't have any item in the ninth slot, only in the first and the eighteenth. To be checked too :)

**Comment by Azounstone** [comment] 2016-12-08 01:02
Hello,

it is very very rare indeed that you trade 2 items to get one and as I said doing the exact same thing in 1.10.x and previous versions all the way back to 1.8 all work. It is just the 1.11 version that does not work.

Thanks for looking into this and I look forward to a fix.

Regards,

**Comment by LaChal** [comment] 2016-12-08 20:16
All is fine unless you try to use chests placed ingame to create shops.
This will be fixed in the next release.

Meanwhile, you can use only chests placed with MCEdit.

You also can edit the `CreateShops.py` filter file in the `stock-filters` directory in your MCEdit install folder.
Just replace the line 123:
```
                if e["id"].value == "Chest":
```

with:
```
                if e["id"].value in ("Chest", "minecraft:chest"):
```

Please, pay attention to the 16 leading spaces. **They must not be removed!**

Note this is a _quick'n'dirty fix_. It was tested and works.
The next version of the filter works, but the code will be a bit different.

**Closed** 2016-12-08 20:25 UTC

**Comment by Azounstone** [comment] 2016-12-08 20:29
Hello,

This allows a chest to be created the way I do it however it really isn't a fix for the issue as there are still lots of problems with it:

1) It creates a generic Villager no matter which type you choose
2) It does not create the generic steve head if you select player head
3) If you do not give it a name it calls it NitWit

![2016-12-08_20 27 05](https://cloud.githubusercontent.com/assets/9461336/21026543/f8a0fac8-bd84-11e6-9cc8-b9bd0ff75cd3.png)

In light of the issues listed above I think to close this as fixed is a little premature.

Regards,

**Comment by LaChal** [comment] 2016-12-08 21:45
Leaving the custom name blank will call it NitWit. Looks like it comes from the game itself.
If you don't want a name for the villager, just uncheck the corresponding box.

Choosing a different type of villager works. (Tested with a butcher.)

Concerning the custom head, the piece of code managing this this was implemented in MCEdit-Unified 1.3.1.0, and has not changed since.
Custom heads works in MC 1.10.2, but no more in 1.11. We'll rework this part of code.

It is fixed because the filter works again. We can't fix a bug we don't know it exists...
Some things has changed in MC 1.11 since 1.10, like some behaviours and the IDs naming conventions.
They are not yet all reported to MCEdit.

**Comment by Azounstone** [comment] 2016-12-08 22:53
Hi,

A number of issues in response to your reply...

Sorry I do not see where you uncheck the corresponding box to not have a name. There is no check box.

Choosing a different type of villager does not work for me. Choosing Green as it refers to always creates the generic white one as per the images.

Custom heads work just fine in 1.11 but not with the filter. If you use this command it will create a villager with a custom head:

/summon villager ~ ~1 ~ {Profession:0,ArmorItems:[{},{},{},{id:skull,Damage:3,Count:1b,tag:{SkullOwner:A_Players_Name}}],ArmorDropChances:[0.085F,0.085F,0.085F,0.0F]}

I still don't think you can say it is fixed because the filter works again because it clearly does not work as it does using 1.10 and that is the basis to judge what it does.

So, at present it just creates a generic villager I can not change its look, I can not give it no name and nor can I add a custom head.

Would you know if you will be able to provide an edited filter that will do all of the above and if so do you have any idea when this might be? I appreciate you are busy etc which is why I ask so I know when.

Thanks again,

**Comment by Azounstone** [comment] 2016-12-08 23:01
UPDATE:

It does create the different types of villagers as long as you do not select Green.

However, when leaving the name area empty it gives it a generic name above it which of course defeats the point of not giving it a name. The filter should be so that when there is no name no name is shown.

Thanks again,

**Comment by Azounstone** [comment] 2016-12-09 07:47
Can you please reply to the other part:

Where in this should I add your edit:

if SkullType == 3 and PlayerName:
Head["tag"] = TAG_Compound()
Head["tag"]["SkullOwner"] = TAG_String(PlayerName)
if legacy == True:
villager["Equipment"] = TAG_List([TAG_Compound(), TAG_Compound(), TAG_Compound(),TAG_Compound(), Head],)
else:
villager["ArmorItems"] = TAG_List([TAG_Compound(), TAG_Compound(), TAG_Compound(), Head])

Can you please edit this to include Head["Count"] = TAG_Short(1)

**Comment by LaChal** [comment] 2016-12-09 20:28
The 'Count' part is already added to the code for the next release.

You may not have noticed I edited one of my post. It contains the steps to add this in the filter.
Basically, right after the line `Head["tag"]["SkullOwner"] = TAG_String(PlayerName)`, add a line `Head["Count"] = TAG_Short(1)` with 8 spaces in front of it.
Again, I tested this on my side with the filter version you have (the MCEdit 1.5.4.1 one with the `line 123 fix` I wrote earlier). It works for MC 1.8, 1.9, 1.10 and 1.11.

**Comment by Azounstone** [comment] 2016-12-09 20:37
Hello,

Thanks for this. I will go to the minecraft community and see if I can get somebody to edit the filter so that it shows no name above a villager when no name is chosen as this is how it use to work previously. Obviously this will mean that there will be a better filter available elsewhere which seems a little silly but as you do not want to address this I am sure you understand me doing this.

Thanks again for your help :)

**Comment by LaChal** [comment] 2016-12-09 20:53
If another filter being able to work around the game behaviour I saw can be written, I'll be glad. (I'm not an expert on how the game works internally, and again, for MC 1.11, just uncheck the box 'Enable Custom Name', no name will be displayed above the villager head.)

If this filter could be embedded in MCEdit, it would obviously be better :smile:

**Comment by Azounstone** [comment] 2016-12-09 21:02
You keep saying to uncheck the box 'Enable Custom Name' and each time I tell you there is no checkbox as can be seen in the image below:

![image1](https://cloud.githubusercontent.com/assets/9461336/21064449/bb1bbf20-be52-11e6-84cc-7b12c11a4f9a.jpg)

I leave the text area empty but it gives the villager a default name.

Please explain where this check box is that you keep mentioning?

**Comment by Azounstone** [comment] 2016-12-09 21:20
UPDATE:

It seems my filter is different to yours so I have downloaded the latest version again and take the filter from it and then edited it and now I have the checkbox you refer to.

All sorted, thanks :)

**Comment by LaChal** [comment] 2016-12-09 21:49
Obviously, 'Warm the yellow carrot' can't work if you don't have a yellow carrot :smile:

I thought I could see this check box in the video you posted. Sorry for the confusion...
