### ISSUE TITLE
NBT not being fully updated when cloning spawners

### ISSUE THREAD

**Issue by Khroki** [Khroki/MCEdit-Unified#684] opened 2016-06-05 19:21 UTC
Some but not all the NBT data is being updated when using the clone tool on spawners. See the following gallery for more information. 

https://drive.google.com/open?id=0B_kwskQW-64EUFNRY193b3ZJM2c

This bug report is from the reddit. May need confirmation.

**Comment by LaChal** [comment] 2016-06-12 09:44
I can't reproduce this on my side.

Any link to the reddit post?

**Comment by Khroki** [comment] 2016-06-13 11:27
Post is on the release topic, https://www.reddit.com/r/MCEdit/comments/4k3g2y/mcedit_1530_for_mc1819_released/ posted by anminmakura, they are Japanese and don't speak English so more information may be difficult to get.

**Comment by LaChal** [comment] 2016-07-24 17:33
The messages are confusing...
Seem to be related to spawners, but they also talk about 'Passengers' tag, which is not related to the spawner.
Anyway, some spawner issue related to coordinates and spawning mob types has been fixed in the commit  469eb99, and the 'Passengers' issue in the commit c7070e6.

Closing this issue now, but we may want to reopen it if the stuff fixed is not what was reported...

**Closed by LaChal** 2016-07-24 17:33 UTC
