### ISSUE TITLE
Remove dependency on X11 for Mac OS X build

### ISSUE THREAD

**Issue by trejkaz** [Khroki/MCEdit-Unified#261] opened 2015-01-07 03:50 UTC
I tried to run mcedit on OSX recently and to my horror found that it still depends on X11, something which I thought was long dead (at least on this platform.)

Anyway, I am trying to figure out *why* it depends on it. As far as I can tell it shouldn't need it, because:
* mcedit only depends on PyGame (as far as I can tell)
* PyGame only depends on SDL (as far as I can tell)
* SDL supports native Quartz already (according to their site)

So I guess any of those three layers could be doing it wrong, but I don't know Python nor SDL well enough to say where the issue is.

**Comment by Khroki** [comment] 2015-01-07 03:56
The SDL mcedit uses is still 1.2, not the newer 2.x revisions, pygame also depends on some other old libraries and is getting pretty behind on the mac front, to make releases we have to build our own pygame which requires a few workarounds as is. Such as working around pygame still relying on Scrap (which was designed for OS9) for clipboard support.

**Comment by trejkaz** [comment] 2015-01-07 04:21
I think what is going on is that SDL 1.2 still bundles X11 in their *default* build even if they don't depend on it. :( Their configure&&make build has a way to disable it, but their Xcode project doesn't seem to.

Also it looks like SDL itself will only build on 10.8 or earlier unless I can figure out how to modify it to remove the dependency on CGDirectPaletteRef.

**Comment by Khroki** [comment] 2015-01-07 04:23
Yeah, stuff like that is why that guide for compiling pygame is so long, compatibility is really shoddy past 1.6/1.7 ish, the build machine originally ran 10.9 and now runs 10.10, so yeah.

The age of the stuff is starting to show, codewarrior's builds have ceased to work on yosemite at this point.

**Comment by trejkaz** [comment] 2015-01-08 06:03
I think I'm part of the way there.

* Download 10.7 SDK (source: https://github.com/phracker/MacOSX-SDKs )
* Fix things in their Xcode project which appear to be wrong (whoever at SDL last got the build to work presumably didn't check in their changes to the project):
    * Base SDK: 10.7
    * OS X Deployment Target: 10.6
* (dodgy?) Commented out a bunch of lines in the config.h which were X11 related
* (dodgy?) Removed a bunch of .c source files from the build

Now when I build the framework, I get a build which appears to work and doesn't nag me to install X11 either. But I'm not happy about the way I achieved those last two steps...

**Comment by Khroki** [comment] 2015-01-08 14:16
Does it need to be the 10.7 sdk? Another part of pygame is currently using the 10.9 sdk in these builds.

**Comment by trejkaz** [comment] 2015-01-08 23:00
Trying to use 10.9 fails because of usage of CGDirectPaletteRef being removed in the 10.9 SDK.

There are similar comments about the issue on other projects dependent on SDL: https://bitbucket.org/gennady/ja2-stracciatella/issue/54/sdl-1215-wont-compile-on-os-x-109

I found one "fix" which just removes the field from the struct, which doesn't seem OK to me because I would have assumed it was there for a reason: http://hg.libsdl.org/SDL/rev/e9466ead70e5

**Comment by Khroki** [comment] 2015-01-19 23:15
Anyway, closing this for now, using an old SDK to avoid using a current version of an old technology seems counter intuitive. If someone finds a way we can reopen this.

**Closed by Khroki** 2015-01-19 23:15 UTC
Labels: OS X, Suggestion

**Comment by trejkaz** [comment] 2015-01-21 10:57
If anything is counterintuitive it is an application forcing me to install an unsupported X11 server in 2015.

**Comment by joerick** [comment] 2015-10-06 12:33
The X11 dependency in pygame is due to the SDL_ttf framework's dependency on a version of libfreetype that's bundled with X11. You can fix that by using `install_name_tool` to point to a bundled version of libfreetype.

```
install_name_tool -change \
    '/usr/X11/lib/libfreetype.6.dylib' \
    '@loader_path/../../../libfreetype.6.dylib' \
    SDL_ttf.framework/Versions/A/SDL_ttf
```

(not a user of this project, just this issue came up while googling for a solution originally)
