### ISSUE TITLE
MCEdit failing to load image files on startup

### ISSUE THREAD

**Issue by Kryceris** [Khroki/MCEdit-Unified#415] opened 2015-06-10 22:50 UTC
So I downloaded MCedit and tried to open my world. However when I opened my level.dat al i go is this: 
![afaf](https://cloud.githubusercontent.com/assets/12833209/8096105/363deb5a-0fdc-11e5-937d-741a62412702.png)

**Comment by TrazLander** [comment] 2015-06-10 23:02
can provide world download?

**Comment by Kryceris** [comment] 2015-06-10 23:04
Yes, just give me a second

**Comment by Kryceris** [comment] 2015-06-10 23:07
http://www.mediafire.com/download/ayci7zy4aockpd3/test_modified_3.zip

**Comment by Rubisk** [comment] 2015-06-10 23:18
What OS are you on? Mac? Do you open the world by going into the MACOSX folder or not?

**Comment by Kryceris** [comment] 2015-06-10 23:21
Yes I am on mac. And using mac i need to go to ~/Library then Application Support then minecraft then saves.

**Comment by Khroki** [comment] 2015-06-11 22:10
Have you tried a newer version, that's a pre NBT editor version.

**Comment by Kryceris** [comment] 2015-06-11 22:22
This is the latest mcedit i found...

**Comment by Kryceris** [comment] 2015-06-11 22:23
1.3.3.0

**Comment by Rubisk** [comment] 2015-06-11 23:21
That picture isn't taken in 1.3.3.0. Please try again in 1.3.3.0

**Comment by TrazLander** [comment] 2015-06-12 02:47
http://www.mcedit-unified.net/

**Comment by Khroki** [comment] 2015-06-12 03:16
Make sure to delete old versions before downloading the new one, it should say 1.3.3.0 at the top and have a NBT editor icon to the right of the chunk control icon, also the go to nether button was renamed and moved.

**Comment by Kryceris** [comment] 2015-06-12 10:33
Oh ok. Thanks for the tip. ;)

**Comment by Kryceris** [comment] 2015-06-12 11:19
Yeah, it was earlier version that I downloaded becouse of error with MCedit.
![screen shot 2015-06-12 at 2 19 34 pm](https://cloud.githubusercontent.com/assets/12833209/8129081/167de620-110e-11e5-9980-95da999e2fc4.png)

**Comment by Khroki** [comment] 2015-06-12 12:45
If you could click open console and post the error, that'd be great.

**Comment by Kryceris** [comment] 2015-06-12 12:56
Mac OSX 10.6.8. And It will be hard to find everything related to mcedit so I'm just gonna paste everything that is on screen after Error.

**Comment by Khroki** [comment] 2015-06-12 13:04
That's fine, yeah we haven't been testing builds on 10.6.8 because alll the mac user devs are on 10.10.x but we'll see what we can do anyway.

**Comment by Kryceris** [comment] 2015-06-12 13:05
http://www.mediafire.com/view/6nlthrqrnlvmhal/Log.txt Here's the link to log

**Comment by Khroki** [comment] 2015-06-12 13:37
Huh, that's strange, it's choking on the icons for the file chooser/NBT editor with a wrong format error, we had similar for a small number of users relating to the splash screen, prob need a fallback put in place. Could you try 1.2.5.0?

**Comment by Kryceris** [comment] 2015-06-12 14:22
Uhm... Ok.

**Comment by codewarrior0** [comment] 2015-06-12 14:30
That smells like the kind of error you get when you build SDL without libpng present, and then build pygame using that incomplete SDL library.

**Comment by Khroki** [comment] 2015-06-12 14:31
the SDL builds are pre-compiled and libpng is present and was used to build pygame, without it terrain.png wouldn't work. It works on the majority of systems but we've had reports of this happening on a few scattered machines, not sure the cause.

**Comment by Khroki** [comment] 2015-06-12 14:36
Specifically the SDL we use can be found here: https://www.libsdl.org/download-1.2.php

**Comment by Kryceris** [comment] 2015-06-12 14:40
Houston we have a problem...

**Comment by Khroki** [comment] 2015-06-12 14:41
If we can figure out what's up though, then it'll fix some people's splash screens which fall back on plain text if it fails to load the image.

**Comment by Kryceris** [comment] 2015-06-12 14:48
![screen shot 2015-06-12 at 5 40 39 pm](https://cloud.githubusercontent.com/assets/12833209/8132393/2d8efbee-112a-11e5-973d-dec49e2dc08e.png)

**Comment by Khroki** [comment] 2015-06-12 14:49
What's the latest version that works?

**Comment by Kryceris** [comment] 2015-06-12 14:50
? Idk.

**Comment by Kryceris** [comment] 2015-06-12 15:05
i have only tried 3 versions

**Comment by codewarrior0** [comment] 2015-06-12 15:56
Yet, `File is not a Windows BMP file` is the error you get when libpng isn't available. I'll be surprised if it goes on to load terrain.png if you skip over the other files.

The SDL builds you are using are built to load libpng at runtime using whatever LoadLibrary() is called on OS X (that is, they were built using the `--enable-png-shared=yes` option to SDL's `configure` script, and this is the default setting). Maybe it's not loading libpng for some reason? I'm not sure exactly how to diagnose that, but I seem to recall a `DYLD_TRACE_MUMBLE_MUMBLE` environment var you could set. If it only happens on 10.6, maybe dyld was changed somehow between 10.6 and 10.10?

Maybe it's related to how your zip file for the OS X builds isn't storing the symbolic links within the frameworks correctly? It has at least three copies of every framework's .dylibs in there.

**Comment by Kryceris** [comment] 2015-06-12 16:36
So what should I do?

**Comment by Khroki** [comment] 2015-06-12 17:40
Actually, dyld and a few other environment things are different between post and pre 10.9, it caused some headaches getting pygame compiled. To test to see if it's all pngs, or just ones added recently, could you try build 1.2.4.0 and 1.1.2.0 and let me know if either work.

**Comment by Kryceris** [comment] 2015-06-12 17:40
Okay.

**Comment by Kryceris** [comment] 2015-06-12 18:30
1.2.4.0 works fine.
![screen shot 2015-06-12 at 9 28 24 pm](https://cloud.githubusercontent.com/assets/12833209/8137172/0901994c-114a-11e5-983e-bdc5b79d21bf.png)

**Comment by Khroki** [comment] 2015-06-12 18:33
Yeah, 1.2.5.0 is when the splash screen was added, and when this problem started, the same problem apparently applies to the new mac file chooser icons and the NBT icons. So we need to figure out why those pngs don't load properly and the game ones do. The compiling environment has been pretty much unchanged since 1.2

**Comment by Kryceris** [comment] 2015-06-12 18:34
Should I still try 1.1.2.0.?

**Comment by Khroki** [comment] 2015-06-12 18:35
Nah, that answers the question as to when it started. Thing now is to figure out what's wrong.

**Comment by Kryceris** [comment] 2015-06-12 18:35
Okay

**Comment by Khroki** [comment] 2015-06-12 18:36
Codewarrior, any thoughts? I think that eliminates problems with the base libraries.

**Comment by codewarrior0** [comment] 2015-06-12 18:46
You're using relative paths when calling `pygame.image.load()` for the splash and the icon files. Try using `directories.getDataDir()` instead, which is how terrain.png is loaded.

**Comment by Khroki** [comment] 2015-06-12 18:47
That explains that, thanks. We'll get it fixed before next release.

**Comment by codewarrior0** [comment] 2015-06-12 18:49
I seem to recall that apps launched from the Finder in 10.6 had their working directory set to `/`. I wonder if that changed in a later version of OS X.

**Comment by Khroki** [comment] 2015-06-12 18:49
That I'm not sure but there were finder changes in 10.9 that messed with a few things, and 10.10 completely breaks old mcedit versions.

**Comment by Kryceris** [comment] 2015-06-12 18:55
So what should I do now?

**Comment by Khroki** [comment] 2015-06-12 18:55
We're going to build a test release for you to try, might take a bit to sort it.

**Comment by Kryceris** [comment] 2015-06-12 18:56
Okay! Thank you! Btw I like how Codebreaker reports everything and You just simplyfy it :)

**Comment by Khroki** [comment] 2015-06-12 18:57
Yeah, used to fixing computers for the computer illiterate :P. You learn how to simplify. Anyway, will post when we have something.

**Comment by Kryceris** [comment] 2015-06-12 19:01
Okay!
Thanks!

**Comment by Khroki** [comment] 2015-06-12 19:17
Dens is asking if you've deleted your mcedit.ini, and if that fixes the latest version.

**Comment by Kryceris** [comment] 2015-06-12 19:22
Uhm.. I don't get the question quite right. Deleted mcedit.ini when, becouse everytime I reinstalled I deleted that file too.

**Comment by Khroki** [comment] 2015-06-12 19:25
Just confirming, Thanks.

**Comment by Kryceris** [comment] 2015-06-12 19:32
O.O

**Comment by Khroki** [comment] 2015-06-12 20:52
Might need to pick this up tomorrow, need to go for now.

**Comment by Kryceris** [comment] 2015-06-12 21:35
Ok

**Comment by Kryceris** [comment] 2015-06-13 16:42
How is it goin'?

**Comment by Kryceris** [comment] 2015-06-14 11:56
How is it going?

**Comment by Khroki** [comment] 2015-06-14 19:57
Yeah, sorry been busy with work, I'll make the build tonight.

**Comment by Kryceris** [comment] 2015-06-14 23:07
Okay, just don't worry too much about me :) If you have something other to do, then do it first. I can always wait :3

**Comment by Kryceris** [comment] 2015-06-16 00:00
How is it going now?

**Comment by Khroki** [comment] 2015-06-16 13:05
Built a test build but it is crashing on the build machine, I'll post when it's working :P.

**Comment by Khroki** [comment] 2015-06-16 19:20
Here ya go, https://www.dropbox.com/s/pk4rbvpbteqsbp2/mcedit.app.zip?dl=0
let us know if it works or not, and we'd like the console output either way if possible, it outputs all console things to the system log you used to get the crash report.

**Comment by LaChal** [comment] 2015-06-16 19:24
Plaese consider that it's a debug build. It won't 'really' work.
You'll have strange things on screen, but, please report. Escpecially the '*** MCEDIT DEBUG' stuff.

**Comment by OniOniOn-** [comment] 2015-06-17 08:02
When will be the next release? Tens of thousands of people are waiting for MCPE support! (Skype takes too long to start)

**Comment by Rubisk** [comment] 2015-06-17 10:14
When it's done, really. Can't do it before that, and it's hard to judge when it will be done. All we need to do is figure out build issues and then test the release, but there's no way of saying when that will be done.

**Comment by Khroki** [comment] 2015-06-17 12:37
Whenever we find a way to make mac pocket work and actually be transferable to other machines.

**Comment by Khroki** [comment] 2015-06-20 02:06
Kryceris, any news on that build?

**Comment by LaChal** [comment] 2015-06-26 19:44
Iguess that the commit won't fix this issue. It looks like that some OSX versions can't find their way in the .app.

We'll see...

**Comment by Kryceris** [comment] 2015-06-29 18:40
It doesn't work. MCedit error. Once more

**Comment by Rubisk** [comment] 2015-06-29 21:43
Could you provide a full output of the mcedit.log and cmd screen?

**Comment by Kryceris** [comment] 2015-07-01 09:14
Uhm.. Ok

**Comment by Rubisk** [comment] 2015-07-05 11:05
Could you then actually do it too? :p

**Comment by naor2013** [comment] 2015-09-05 18:39
Does it still happen and can you please send the mcedit.log file and the console output? Without more info, we'll have to close this issue

**Comment by Kryceris** [comment] 2015-09-13 07:28
Is it still Important to figure this error out?

**Closed** 2015-09-13 08:40 UTC
Labels: Crash, OS X
