### ISSUE TITLE
Error when dragging outside of the world with the Fill tool

### ISSUE THREAD

**Issue by quat1024** [Khroki/MCEdit-Unified#520] opened 2015-10-25 23:12 UTC
MCEdit gives an error when entering an outside-of-the-world area with the Fill tool.

### Reproduction steps
1. Delete a chunk/find the edge of the generated world
2. Use the Fill tool (part of the Brush tool)
3. Click and hold the mouse on an area inside the world
4. Drag the mouse outside the world
5. Error

### Error dialog details
`Error during <function mouseDrag at 0x000000000DB033C8>: TypeError('zip argument #1 must support iteration',)`

### Version info
MC Edit Unified v1.4.0.1 for Minecraft 1.8/1.9 / World generated in Minecraft 1.8.8 / Windows 7 64bit 

### Video demonstration
https://youtu.be/nQlMOfWhf2I

**Comment by LaChal** [comment] 2015-10-26 19:08
Hmmm...

I can't reproduce this issue now. I'll have another try with a fresh MCEdit install.

Wainting for my test results, can you, please, post the `mcedit.log` file you can find in MCEdit install folder, and the conent of the console?

**Comment by jamaa** [comment] 2015-11-05 18:55
MCEdit also crashes when I try to select chunks in chunk mode and accidentally drag my mouse beyond the edge of the generated world. I'm assuming this is a similar/the same issue. I'm attaching a screenshot of the console and here's a link to the mcerror.log: http://pastebin.com/feyxHYwb .
Using MCEdit 1.4.0.1 on Windows 10.
![console](https://cloud.githubusercontent.com/assets/90166/10978343/afaaba5c-83f6-11e5-9d83-31bd40d31923.png)

**Comment by LaChal** [comment] 2015-11-08 11:24
These two issues will be fixed in the next release.

**Closed by LaChal** 2015-11-08 11:24 UTC
