### ISSUE TITLE
Heads render strangely

### ISSUE THREAD

**Issue by yrsegal** [Khroki/MCEdit-Unified#301] opened 2015-02-10 15:15 UTC
Now, I have a slight confusion here. Not at all sure what's going on.
I could see my head (and the base layer) rendered through quartz. But destruc7i0n's head stayed obscured.
![screen shot 2015-02-09 at 7 54 46 pm](https://cloud.githubusercontent.com/assets/6596492/6129605/97b583c6-b10d-11e4-8941-24e01d7c5db8.png)
![screen shot 2015-02-10 at 10 13 59 am](https://cloud.githubusercontent.com/assets/6596492/6129606/97b805f6-b10d-11e4-8fe8-79b7c03403fe.png)
MCEdit version is commit 414248d0b72850b7ed08cf375d7011ff8187f9e0

**Comment by TrazLander** [comment] 2015-02-27 11:09
Seems to render every head that I placed in my world except that one...which is "Notch".

**Comment by Podshot** [comment] 2015-02-27 14:47
Hmm, it may be the renderer rendering the manually placed heads first, then blocks, then the heads that were already in the world. Does this still happen after restarting MCEdit?

**Comment by TrazLander** [comment] 2015-02-27 16:30
most of those heads I added using mcedit. And ya those same heads are unchanged all but Notch when I restart mcedit.

**Comment by TrazLander** [comment] 2015-03-02 22:36
Ok, i can't actually reproduce this issue with the name "destruc7i0n". @yrsegal is this still happening? If so, what is computer OS?

**Comment by yrsegal** [comment] 2015-03-02 23:18
I'm Mac OS X Yosemite, latest version. It continues to happen, with some
heads sometimes rendering behind blocks and sometimes not.

These aren't head blocks, by the way, but actual players.


Signing off,

Wire Segal

**Comment by TrazLander** [comment] 2015-03-02 23:38
could you send me the world download where it's happening? Maybe something with that.

**Comment by yrsegal** [comment] 2015-03-02 23:57
sure, it's... hm. it's a world we're releasing soon to the public, but not
yet, so i'll see if i can private message it to you somehow.


Signing off,

Wire Segal

**Comment by yrsegal** [comment] 2015-04-16 15:03
Any news on this?

**Comment by TrazLander** [comment] 2015-04-18 07:55
Might not work this out atm since @Podshot may look into a better skin caching method which would probably accidentally fix this anyway. Though, if I get around to it I may try to work out how MCEdit is ending up with particular skulls that become invisible. I have a feeling it could be usercache list order....or something.

**Comment by Halogen002** [comment] 2015-06-14 18:42
In Minecraft 1.0.0, the bottom textures of heads were flipped, and MCEdit likely wasn't updated for that. I tried creating an issue (#417) for that, but Rubisk said it was a duplicate of this one?

**Comment by Podshot** [comment] 2015-06-14 21:59
I won't be able to access my dev environment for at least 3 weeks. I'll put both issues  at the top of my TODO list, but if anyone wants to tackle them, by all means go ahead

**Comment by TrazLander** [comment] 2015-07-07 08:42
This looks resolved, and it's pretty super minor anyway. But on a side note head rendering on the master seems to be completely broken for me anyway :P

**Closed by TrazLander** 2015-07-07 08:42 UTC
Labels: Annoying, Bug
